/* eslint-disable max-len */
const { __ = f => f } = window.wp?.i18n || {};

export const ALL_TEXTS = {
  LETS_START: __("Let's start", 'jotform-ai-chatbot'),
  BACK: __('Back', 'jotform-ai-chatbot'),
  NEXT: __('Next', 'jotform-ai-chatbot'),
  READ_TO_BUILD_YOUR_AI: __('Ready to build your AI Chatbot?', 'jotform-ai-chatbot'),
  CREATE_AND_CUSTOMIZE_YOUR_AI: __('Create and customize your AI Chatbot in minutes', 'jotform-ai-chatbot'),

  SETUP_YOUR_AI_CHATBOT: __('Setup Your AI Chatbot', 'jotform-ai-chatbot'),
  USE_TEMPLATE_READY_OR_START_FROM_SCRATCH: __('You can use our ready-to-use prompts or start from scratch.', 'jotform-ai-chatbot'),
  GREETING: __('Greeting', 'jotform-ai-chatbot'),
  SHOW_A_MESSAGE: __('Show a message to greet users', 'jotform-ai-chatbot'),
  HOW_CAN_I_HELP_YOU: __('Hi! How can I help you?', 'jotform-ai-chatbot'),
  PULSING: __('Pulsing', 'jotform-ai-chatbot'),
  ADD_A_PULSE_EFFECT: __('Add a pulsing effect to the avatar', 'jotform-ai-chatbot'),
  POSITION: __('Position', 'jotform-ai-chatbot'),
  LEFT: __('Left', 'jotform-ai-chatbot'),
  RIGHT: __('Right', 'jotform-ai-chatbot'),
  CHOOSE_THE_AI_AGENT: __("Choose the AI Agent's screen position", 'jotform-ai-chatbot'),

  COLOR_SCHEME: __('COLOR SCHEME', 'jotform-ai-chatbot'),
  AGENT_BACKGROUND_STYLE: __('AGENT BACKGROUND STYLE', 'jotform-ai-chatbot'),
  START_COLOR: __('Start Color', 'jotform-ai-chatbot'),
  END_COLOR: __('End Color', 'jotform-ai-chatbot'),
  CHAT_STYLE: __('CHAT STYLE', 'jotform-ai-chatbot'),
  CHAT_BACKGROUND_COLOR: __('Chat Background Color', 'jotform-ai-chatbot'),
  FONT_FAMILY: __('Font Family', 'jotform-ai-chatbot'),
  FONT_COLOR: __('Font Color', 'jotform-ai-chatbot'),
  CHAT_THEME_COLOR: __('Chat Theme Color', 'jotform-ai-chatbot'),
  BUTTON_STYLE: __('BUTTON STYLE', 'jotform-ai-chatbot'),
  BUTTON_COLOR: __('Button Color', 'jotform-ai-chatbot'),
  ICON_COLOR: __('Icon Color', 'jotform-ai-chatbot'),
  DEFAULT: __('Default', 'jotform-ai-chatbot'),
  MINIMAL: __('Minimal', 'jotform-ai-chatbot'),
  CREATE_AI_CHATBOT: __('Create AI Chatbot', 'jotform-ai-chatbot'),
  CREATE: __('Create', 'jotform-ai-chatbot'),

  DESCRIBE_THE_AGENT_YOU_WANT_TO_CREATE: __('Describe the agent you want to create', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  EXAMPLE_PROVIDE_CUSTOMER_SUPPORT_BY_ANSWERING_FAQS_AND_GUIDING_USERS_THROUGH: __('Example: Provide customer support by answering FAQs and guiding users through troubleshooting steps.', 'jotform-ai-chatbot'),
  FEEDBACK: __('Feedback', 'jotform-ai-chatbot'),
  SHOW_AI_CHATBOT_ON: __('Show AI Chatbot on', 'jotform-ai-chatbot'),
  CHOOSE_PAGES_THE_AI_CHATBOT_WILL_BE_SHOWN_ON: __('Choose pages the AI Chatbot will be shown on.', 'jotform-ai-chatbot'),

  VIEW_CONVERSATIONS: __('View Conversations', 'jotform-ai-chatbot'),

  GIVE_FEEDBACK: __('Give Feedback', 'jotform-ai-chatbot'),

  REMOVE_CHATBOT_FROM_WEBSITE: __('Remove Chatbot from Website?', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  CLICK_REMOVE_FROM_WEBSITE_TO_PERMANENTLY_DELETE: __('Click Remove from Website to permanently delete this chatbot’s site-specific settings and remove it from your website.', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  YOUR_CHATBOT_AND_ITS_TRANING_DATA_WILL_STILL_BE_SAVED: __('Your chatbot and its training data will still be saved, but you’ll need to configure site-specific settings again if you add it back.', 'jotform-ai-chatbot'),
  UNPUBLISH_CHATBOT_FROM_WEBSITE: __('Unpublish Chatbot from Website?', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  CLICK_UNPUBLISH_TO_REMOVE_THE_CHATBOT: __('Click Unpublish to remove the chatbot from your website while keeping its site-specific settings saved. You can republish it later without losing your setup.', 'jotform-ai-chatbot'),
  YOUR_CHATBOT_AND_ITS_TRANING_DATA_WILL_REMAIN_SAVED: __('Your chatbot and its training data will remain saved.', 'jotform-ai-chatbot'),

  OPEN_A_SUPPORT_TICKET: __('Open a Support Ticket', 'jotform-ai-chatbot'),
  YOU_WILL_BE_REDIRECTED_TO_SUPPORT: __('You’ll be redirected to the Jotform AI Chatbot support page on WordPress.org.', 'jotform-ai-chatbot'),
  TO_SUBMIT_A_TICKET_PLEASE: __('To submit a ticket, please make sure you’re [1[logged in]] or [2[create a free WordPress.org account.]]', 'jotform-ai-chatbot'),

  UNPUBLISH: __('Unpublish', 'jotform-ai-chatbot'),
  UNPUBLISHING: __('Unpublishing...', 'jotform-ai-chatbot'),

  REMOVE_FROM_WEBSITE: __('Remove from Website', 'jotform-ai-chatbot'),
  REMOVE_FROM_WEBSITE_2: __('Remove from website', 'jotform-ai-chatbot'),
  REMOVING: __('Removing...', 'jotform-ai-chatbot'),

  ANIMATION_TITLE: __('Chatbot Introduction Animation', 'jotform-ai-chatbot'),

  AGENT_AVATAR: __('Agent Avatar', 'jotform-ai-chatbot'),
  SELECT_AN_AVATAR: __('Select an avatar for your agent.', 'jotform-ai-chatbot'),
  AI_PERSONA: __('AI Persona', 'jotform-ai-chatbot'),

  CURRENT_AVATAR: __('Current Avatar', 'jotform-ai-chatbot'),

  AGENT_NAME: __('Agent Name', 'jotform-ai-chatbot'),
  GIVE_A_NAME_TO_YOUR_AGENT_THAT_WILL_BE_DISPLAYED_IN_THE_CONVERSATION: __('Give a name to your agent that will be displayed in the conversation', 'jotform-ai-chatbot'),
  AGENT_ROLE: __('Agent Role', 'jotform-ai-chatbot'),
  DESCRIPTION_YOUR_AGENTS_JOB_TITLE: __('Describe your agent’s job title', 'jotform-ai-chatbot'),
  CHATTINESS: __('Chattiness', 'jotform-ai-chatbot'),
  SPECIFY_THE_DESIRED_LEVEL_OF_DETAIL_IN_THE_AGENTS_RESPONSES: __("Specify the desired level of detail in the agent's responses", 'jotform-ai-chatbot'),
  GO_TO_PRICING: __('Go to Pricing', 'jotform-ai-chatbot'),
  YOU_HAVE_REACHED_YOUR_LIMIT: __("You've reached your AI Chatbot limit.", 'jotform-ai-chatbot'),
  DELETE_EXISTING_AGENT: __('Delete an existing agent or upgrade to add more.', 'jotform-ai-chatbot'),

  DESCRIBE: __('Describe', 'jotform-ai-chatbot'),
  SELECT_FROM_AGENTS: __('Select from My AI Agents', 'jotform-ai-chatbot'),
  DEFAULT_LANGUAGE: __('Default Language', 'jotform-ai-chatbot'),
  SELECT_THE_LANGUAGE: __('Select the language in which your agents greet users', 'jotform-ai-chatbot'),
  TONE_OF_VOICE: __('Tone of Voice', 'jotform-ai-chatbot'),
  SELECT_HOW_TO_COMMUNICATE: __('Select how you would like the AI to communicate', 'jotform-ai-chatbot'),

  HOW_TO_USE_JOTFORM_AI_CHATBOT: __('How to use Jotform AI Chatbot?', 'jotform-ai-chatbot'),
  AGENT_STYLE: __('Agent style', 'jotform-ai-chatbot'),
  VISIBILITY: __('Visibility', 'jotform-ai-chatbot'),
  KNOWLEDGE_BASE: __('Knowledge base', 'jotform-ai-chatbot'),
  GREETING_MESSAGE: __('Greeting Message', 'jotform-ai-chatbot'),
  SHOW_A_MESSAGE_TO_GREET_USERS: __('Show a message to greet users', 'jotform-ai-chatbot'),
  CHAT_GUIDELINES: __('Chat Guidelines', 'jotform-ai-chatbot'),
  SET_CLEAR_RULES: __('Set clear rules for how your agent should respond in chat channels', 'jotform-ai-chatbot'),
  ADD_NEW: __('Add New', 'jotform-ai-chatbot'),
  VISIBLE_ON: __('Visible on', 'jotform-ai-chatbot'),
  CHOOSE_WHERE_THE_CHATBOT_SHOULD_APPEAR: __('Choose where the chatbot should appear', 'jotform-ai-chatbot'),
  OPEN_BY_DEFAULT: __('Open by default', 'jotform-ai-chatbot'),
  CHOOSE_WHEN_CHATBOT_WILL_APPEAR: __('Choose when chatbot will appear', 'jotform-ai-chatbot'),
  ADVANCED_VISIBILITY: __('Advanced Visibility', 'jotform-ai-chatbot'),
  CHOOSE_WHERE_CHATBOT_WILL_BE_SHOWN_OR_HIDDEN: __('Choose where chatbot will be shown or hidden', 'jotform-ai-chatbot'),
  SHOW_ON: __('Show on', 'jotform-ai-chatbot'),
  HIDE_ON: __('Hide on', 'jotform-ai-chatbot'),
  DO_NOT_OPEN_AUTOMATICALLY: __('Do not open automatically', 'jotform-ai-chatbot'),
  ALWAYS_OPEN: __('Always open', 'jotform-ai-chatbot'),
  OPEN_AFTER_FIVE_SECONDS: __('Open after 5 seconds', 'jotform-ai-chatbot'),
  OPEN_AFTER_TEN_SECONDS: __('Open after 10 seconds', 'jotform-ai-chatbot'),
  DO_YOU_WANT_TO_DELETE_INSTRUCTION: __('Do you want to delete this instruction?', 'jotform-ai-chatbot'),
  THIS_INSTRUCTION_WILL_BE_REMOVED_PERMANENTLY: __('This instruction will be removed permanently.', 'jotform-ai-chatbot'),
  NO_KEEP: __('No, keep', 'jotform-ai-chatbot'),
  YES_DELETE: __('Yes, delete', 'jotform-ai-chatbot'),
  ADD: __('Add', 'jotform-ai-chatbot'),
  ENTER_URL: __('Enter URL', 'jotform-ai-chatbot'),
  URL: __('URL', 'jotform-ai-chatbot'),
  REMOVE_AI_CHATBOT_FROM_MY_WEBSITE: __('Remove AI Chatbot from My Website', 'jotform-ai-chatbot'),
  ANONYMOUS: __('Anonymous', 'jotform-ai-chatbot'),
  CONVERSATIONS: __('Conversations', 'jotform-ai-chatbot'),
  SEE_CONVERSATIONS_ON_JOTFORM: __('See conversation on Jotform', 'jotform-ai-chatbot'),
  GO_TO_JOTFORM: __('Go to Jotform', 'jotform-ai-chatbot'),
  PREVIEW: __('Preview', 'jotform-ai-chatbot'),
  PUBLISH: __('Publish', 'jotform-ai-chatbot'),
  PUBLISHED: __('Published', 'jotform-ai-chatbot'),
  AUTO_TRAINED_KNOWLEDGE: __('Auto-trained knowledge', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  YOUR_AI_CHATBOT_IS_AUTOMATICALLY_TRAINED: __("Your AI chatbot is automatically trained with your website's content, such as pages, posts, and more, to provide a smarter, more relevant experience for your users.", 'jotform-ai-chatbot'),
  CONVERSATIONS_WILL_BE_LISTED_HERE: __('Conversations will be listed here', 'jotform-ai-chatbot'),
  YOU_DONT_HAVE_ANY_CONVERSATIONS: __("You don't have any conversations", 'jotform-ai-chatbot'),
  CONTINUE: __('Continue', 'jotform-ai-chatbot'),
  YOUR_AI_CHATBOT_WILL_BE_LIVE_ON_ALL_PAGES: __('Your AI chatbot will be live on all pages once published.', 'jotform-ai-chatbot'),
  YOUR_AI_CHATBOT_IS_CURRENTLY_LIVE_ON_ALL_PAGES: __('Your AI chatbot is currently live on all pages.', 'jotform-ai-chatbot'),
  LAYOUT: __('Layout', 'jotform-ai-chatbot'),
  EXTENDED: __('Extended', 'jotform-ai-chatbot'),
  CHOOSE_HOW_CHATBOT_APPEARS: __('Choose how the chatbot appears on your website', 'jotform-ai-chatbot'),

  WHATS_NEW: __('What’s new 🔥', 'jotform-ai-chatbot'),
  GET_THE_LATEST_CHANGES_AND_UPDATES: __('Get the latest changes and updates', 'jotform-ai-chatbot'),
  TRY_IT_NOW: __('Try it now', 'jotform-ai-chatbot'),
  SETTINGS: __('Settings', 'jotform-ai-chatbot'),
  GENERAL: __('General', 'jotform-ai-chatbot'),
  AGENT_SKILLS: __('Agent Skills', 'jotform-ai-chatbot'),
  WOO_COMMERCE: __('WooCommerce', 'jotform-ai-chatbot'),
  WOOCOMMERCE_STORE_SETTINGS: __('WOOCOMMERCE STORE SETTINGS', 'jotform-ai-chatbot'),
  CONSUMER_KEY: __('Consumer Key', 'jotform-ai-chatbot'),
  YOUR_WOO_COMMERCE_API_KEY: __('Your WooCommerce API key used to connect the store.', 'jotform-ai-chatbot'),
  CONSUMER_SECRET: __('Consumer Secret', 'jotform-ai-chatbot'),
  YOUR_WOO_COMMERCE_API_SECRET: __('Your WooCommerce API secret for secure access.', 'jotform-ai-chatbot'),
  FIND_PRODUCTS: __('Find Products', 'jotform-ai-chatbot'),
  HELPS_CUSTOMERS_SEARCH_OR_FILTER_PRODUCTS: __('Helps customers search or filter products by attributes such as price, size, or color.', 'jotform-ai-chatbot'),
  RECOMMEND_PRODUCTS: __('Recommend Products', 'jotform-ai-chatbot'),
  SUGGESTS_BEST_SELLERS: __('Suggests best sellers, trending items, or personalized recommendations to guide customer choices.', 'jotform-ai-chatbot'),
  ADD_PRODUCTS_TO_CART: __('Add Products to Cart', 'jotform-ai-chatbot'),
  ADD_ITEMS_TO_THE_SHOPPING_CART: __(' Adds items to the shopping cart based on customer requests.', 'jotform-ai-chatbot'),
  SHOW_ORDER_STATUS: __('Show Order Status', 'jotform-ai-chatbot'),
  PRODVIDES_REAL_TIME_UPDATES: __('Provides real-time updates so customers can track their orders with ease. ', 'jotform-ai-chatbot'),
  MANAGE_REFUNDS: __('Manage Refunds', 'jotform-ai-chatbot'),
  HANDLE_REFUND_REQUESTS: __('Handle customer refund requests, approve or decline them, and share status updates.', 'jotform-ai-chatbot'),
  CONNECT: __('Connect Store', 'jotform-ai-chatbot'),
  KEY_PLACEHOLDER: __('Please enter your key here', 'jotform-ai-chatbot'),
  SECRET_PLACEHOLDER: __('Please enter your secret here', 'jotform-ai-chatbot'),
  CHATBOT_ABILITIES: __('CHATBOT ABILITIES', 'jotform-ai-chatbot'),
  COMING_SOON: __('Coming Soon', 'jotform-ai-chatbot'),
  DISCONNECT_STORE: __('Disconnect Store', 'jotform-ai-chatbot'),
  UPGRADE_PLAN: __('Upgrade Plan', 'jotform-ai-chatbot'),
  PUBLISHING: __('Publishing...', 'jotform-ai-chatbot'),
  CANCEL: __('Cancel', 'jotform-ai-chatbot'),
  CONNECTED_CHATBOT: __('Connected Chatbot', 'jotform-ai-chatbot'),
  CONNECTED_JOTFORM_ACCOUNT: __('Connected Jotform Account', 'jotform-ai-chatbot'),
  LOGOUT: __('Logout', 'jotform-ai-chatbot'),
  LOGGINGOUT: __('Logging out...', 'jotform-ai-chatbot'),
  LOGOUT_DIALOG_TITLE: __('Log Out from Your Account?', 'jotform-ai-chatbot'),
  LOGOUT_DIALOG_DESC: __('Click Logout to sign out of your account. Your settings and preferences will remain saved, and you can log back in anytime without losing your setup.', 'jotform-ai-chatbot'),
  LOGOUT_DIALOG_INFO: __('All your data and saved progress will remain secure.', 'jotform-ai-chatbot'),
  CONNECTED_STORE: __('Connected Store', 'jotform-ai-chatbot'),
  // eslint-disable-next-line max-len
  NETWORK_ERROR_DESC_ENTERPRISE: __('Unable to connect to the server. Please check your internet connection and try again. If you’re using an enterprise account, contact your system administrator for assistance.', 'jotform-ai-chatbot'),
  UNAUTHORIZED_API_KEY_DESC: __('You don’t have permission to use this plugin. Please contact your system administrator to enable access.', 'jotform-ai-chatbot'),

  WOOCOMMERCE_PLUGIN_NOT_INSTALLED: __('To use this feature, please make sure the [1[WooCommerce plugin is installed and active]] on your site.', 'jotform-ai-chatbot'),
  WOOCOMMERCE_CONSUMER_SECRET_AND_KEY: __('You can create your Consumer Secret and Key in [1[WooCommerce > Settings > Advanced > REST API.]]', 'jotform-ai-chatbot'),
  WOOCOMMERCE_PERMALINK_ERROR: __('Your site is using [1[Plain permalinks]], which prevents the integration from working. Please update your permalink settings [2[here.]]', 'jotform-ai-chatbot'),
  NO_AGENT_ERROR: __('Please [1[create an agent]] first to connect your store.', 'jotform-ai-chatbot'),
  NETWORK_ERROR_TITLE: __('Connection issue', 'jotform-ai-chatbot'),
  NETWORK_ERROR_DESC_NETWORK: __('Can’t connect to the server. Please check your internet connection or try again.', 'jotform-ai-chatbot'),
  UNAUTHORIZED_API_KEY_TITLE: __('Unauthorized Access', 'jotform-ai-chatbot'),
  ALMOST_FULL_LIMIT_WARNING_TEXT: __('You’re close to your [1[{limit}]] [2[limit]]. Upgrade to keep your agent active.', 'jotform-ai-chatbot'),
  OVERLIMIT_LIMIT_WARNING_TEXT: __('You’ve reached your [1[{limit}]] [2[limit]]. Upgrade to keep your agent active.', 'jotform-ai-chatbot'),
  UPGRADE_NOW: __('Upgrade Now', 'jotform-ai-chatbot'),
  LOCALHOST_ERROR: __('WooCommerce features can’t be used on a [1[local server.]]', 'jotform-ai-chatbot'),
  SHOW_MORE: __('Show more', 'jotform-ai-chatbot'),
  LOADING: __('Loading...', 'jotform-ai-chatbot'),
  GO_TO_SUPPORT_PAGE: __('Go to support page', 'jotform-ai-chatbot'),
  GET_SUPPORT: __('Get Support', 'jotform-ai-chatbot'),
  CHANGE_IMAGE: __('Change Image', 'jotform-ai-chatbot'),
  SAVE: __('Save', 'jotform-ai-chatbot'),
  CUSTOM_AVATAR: __('Custom Avatar', 'jotform-ai-chatbot'),
  EDIT_AVATAR: __('Edit Avatar', 'jotform-ai-chatbot'),
  CHANGE_AVATAR: __('Change Avatar', 'jotform-ai-chatbot'),
  IMAGE_SIZE: __('Image Size', 'jotform-ai-chatbot'),
  ENTER_QUESTION: __('Enter a brief, clear question that you\'d like the chatbot to answer.', 'jotform-ai-chatbot'),
  PROVIDE_ANSWER: __('Provide a detailed and informative answer that will help the chatbot respond accurately to the question.', 'jotform-ai-chatbot'),
  ANSWER: __('Answer', 'jotform-ai-chatbot'),
  TRAIN_THE_AI: __('Train the AI based on your questions & answers', 'jotform-ai-chatbot'),
  QUESTION: __('Question', 'jotform-ai-chatbot'),
  INFORMATION_FOR_YOUR_CHATBOT: __('Information for Your Chatbot', 'jotform-ai-chatbot'),
  ENTER_ACCURATE_INFO_YOUR_AI_CAN_USE_AS_ANSWERS: __('Enter accurate info your AI can use as answers', 'jotform-ai-chatbot'),
  COMPANY_OVERVIEW: __('Company overview, product features, customer FAQs, service guidelines...', 'jotform-ai-chatbot'),
  UPLOAD_A_PDF: __('Please upload a PDF or DOCX file', 'jotform-ai-chatbot'),
  UPLOAD_A_DOCUMENT: __('Upload a Document', 'jotform-ai-chatbot'),
  DRAG_AND_DROP_YOUR_FILE: __('Drag and drop your files here or', 'jotform-ai-chatbot'),
  TRAIN_YOUR_CHATBOT: __('Train your chatbot with uploaded content', 'jotform-ai-chatbot'),
  ENTER_A_URL: __('Enter a URL', 'jotform-ai-chatbot'),
  PROVIDE_A_URL_FOR_YOUR_CHATBOT_TO_ANALYZE: __('Provide a URL for your chatbot to analyze', 'jotform-ai-chatbot'),
  CRAWL: __('Crawl', 'jotform-ai-chatbot'),
  MATERIAL_CONFIRMATION_MODAL: __('Material Confirmation Modal', 'jotform-ai-chatbot'),
  DO_YOU_WANT_TO_DELETE_THIS_MATERIAL: __('Do you want to delete this material?', 'jotform-ai-chatbot'),
  ONCE_REMOVED_THE_AI_AGENT_WILL_NO_LONGER_HAVE_ACCESS_TO_IT: __('Once removed, the AI Agent will no longer have access to it.', 'jotform-ai-chatbot'),
  AN_ERROR_OCCURED: __('An error occured.', 'jotform-ai-chatbot'),
  ANSWER_NEEDED: __('Answer needed.', 'jotform-ai-chatbot'),
  SEARCH: __('Search', 'jotform-ai-chatbot'),

  // WooCommerce connection error related texts - rendered dynamically based on error code (woocommerce: { errorCode })
  WOO_MISSING_CREDENTIALS: __('Store URL, consumer key and consumer secret are all required.', 'jotform-ai-chatbot'),
  WOO_INVALID_CREDENTIAL_FORMAT: __('Consumer key must start with "ck_" and consumer secret must start with "cs_".', 'jotform-ai-chatbot'),
  WOO_STORE_UNREACHABLE: __('Could not connect to the store. Please verify the store URL is correct and the store is online.', 'jotform-ai-chatbot'),
  WOO_STORE_BLOCKING_REQUEST: __('The store appears to be blocking external API requests. The store owner should whitelist server-to-server requests in their firewall or security plugin (e.g. Wordfence).', 'jotform-ai-chatbot'),
  WOO_STORE_REDIRECT: __('The store URL is redirecting to another address. Please use the final destination URL (e.g. ensure HTTP/HTTPS and www/non-www match the store\'s canonical URL).', 'jotform-ai-chatbot'),
  WOO_STORE_SERVER_ERROR: __('The store\'s server is experiencing issues. This is usually temporary — please try again in a few minutes.', 'jotform-ai-chatbot'),
  WOO_CLOUDFLARE_ORIGIN_ERROR: __('The store\'s server is experiencing issues behind Cloudflare. This is usually temporary — please try again in a few minutes.', 'jotform-ai-chatbot'),
  WOO_INVALID_CREDENTIALS: __('The consumer key or secret was rejected by the store. Please double-check your WooCommerce API credentials.', 'jotform-ai-chatbot'),
  WOO_ACCESS_FORBIDDEN: __('Access to the store API was forbidden. This may be caused by an IP block, a security plugin or insufficient API key permissions.', 'jotform-ai-chatbot'),
  WOO_CLOUDFLARE_BOT_PROTECTION: __('This store\'s Cloudflare bot protection is blocking API access. The store owner needs to whitelist server-to-server requests or disable Bot Fight Mode for the WooCommerce API path (/wp-json/wc/).', 'jotform-ai-chatbot'),
  WOO_REST_API_NOT_FOUND: __('The WooCommerce REST API endpoint was not found. Please ensure WooCommerce is installed and active, and that WordPress permalinks are not set to "Plain" (Settings → Permalinks).', 'jotform-ai-chatbot'),
  WOO_RATE_LIMITED: __('The store is rate-limiting requests. Please wait a moment and try again.', 'jotform-ai-chatbot'),
  WOO_UNEXPECTED_RESPONSE: __('An unexpected error occurred while trying to reach the store. Please try again.', 'jotform-ai-chatbot'),
  WOO_UNEXPECTED_HTTP_CODE: __('Received an unexpected response from the store. Please verify the store URL and try again.', 'jotform-ai-chatbot')
};
